In [1]:
import pandas as pd

In [2]:
# for bosch-ai parameters
file_path_3 = 'eda_3_output_transformed_train_subtask2.csv' 

# for default parameters
file_path_2 = 'eda_2_output_transformed_train_subtask2.csv'

In [3]:
# Read the CSV file into a DataFrame

#bosch-ai
df3 = pd.read_csv(file_path_3)
#default eda parameters
df2 = pd.read_csv(file_path_2)

In [4]:
print(df3.columns)

Index(['corpus', 'doc_id', 'sent_id', 'eg_id', 'index', 'text',
       'causal_text_w_pairs', 'num_rs'],
      dtype='object')

In [5]:
# Remove <sig1> and </sig1> from 'text' column
df2['text'] = df2['text'].str.replace('<sig1>', '').str.replace('</sig1>', '')
df3['text'] = df3['text'].str.replace('<sig1>', '').str.replace('</sig1>', '')

In [8]:
# Define the patterns to check for
patterns = ['<', '>', 'arg0', 'arg1', 'sig0', 'sig1','sig2']
# Create a boolean mask indicating if any of the patterns exist in each sentence
mask2 = df2['text'].str.contains('|'.join(patterns))
mask3 = df3['text'].str.contains('|'.join(patterns))

# Filter the DataFrame based on the mask
filtered_df2 = df2[mask2]
# Print the index column values of sentences containing the specified patterns
print("Index values of sentences with specified patterns-2:")
print(filtered_df2['index'])

print('')
print('')

# Filter the DataFrame based on the mask
filtered_df3 = df3[mask3]
# Print the index column values of sentences containing the specified patterns
print("Index values of sentences with specified patterns-3:")
print(filtered_df3['index'])

Index values of sentences with specified patterns-2:
Series([], Name: index, dtype: object)


Index values of sentences with specified patterns-3:
Series([], Name: index, dtype: object)

In [7]:
# Remove <sig2> and </sig2> from the 'text' column
df2['text'] = df2['text'].str.replace('<sig2>', '').str.replace('</sig2>', '')

# Remove <sig2> and </sig2> from the 'text' column
df3['text'] = df3['text'].str.replace('<sig2>', '').str.replace('</sig2>', '')

In [9]:
df3.to_csv('processed_eda_3_output_transformed_train_subtask2.csv', index=None)
df2.to_csv('processed_eda_2_output_transformed_train_subtask2.csv', index=None)

In [10]:
# for bosch-ai parameters
file_3 = 'processed_eda_3_output_transformed_train_subtask2.csv' 

# for default parameters
file_2 = 'processed_eda_2_output_transformed_train_subtask2.csv'

In [11]:
# Read the CSV file into a DataFrame

#bosch-ai
df_3 = pd.read_csv(file_3)
#default eda parameters
df_2 = pd.read_csv(file_2)

In [12]:
import re
pattern = r'<(.*?)>'
unique_values = set()

for index, row in df_2.iterrows():
    text = row['causal_text_w_pairs']
    matches = re.findall(pattern, text)
    unique_values.update(matches)

# Print unique values
print("Unique Values inside <>:")
for value in unique_values:
    print(value)

Unique Values inside <>:
sig0
/sig1
/sig0
sig1
sig2
arg0
/arg0
/arg1
arg1
/sig2

In [13]:
# Define the values to convert to uppercase
values_to_convert = ['arg0', '/arg1', '/sig1', 'sig0', '/sig0', 'arg1', '/sig2', '/arg0', 'sig1', 'sig2']

# Convert only the specified values to uppercase in the 'causal_text_w_pairs' column
for value in values_to_convert:
    df_2['causal_text_w_pairs'] = df_2['causal_text_w_pairs'].str.replace(value, value.upper())

df_2.to_csv('processed_eda_2_output_transformed_train_subtask2.csv', index=None)

In [14]:
# Define the values to convert to uppercase
values_to_convert = ['arg0', '/arg1', '/sig1', 'sig0', '/sig0', 'arg1', '/sig2', '/arg0', 'sig1', 'sig2']

# Convert only the specified values to uppercase in the 'causal_text_w_pairs' column
for value in values_to_convert:
    df_3['causal_text_w_pairs'] = df_3['causal_text_w_pairs'].str.replace(value, value.upper())

df_3.to_csv('processed_eda_3_output_transformed_train_subtask2.csv', index=None)

In [15]:
# for bosch-ai parameters
file_3 = 'processed_eda_3_output_transformed_train_subtask2.csv' 

# for default parameters
file_2 = 'processed_eda_2_output_transformed_train_subtask2.csv'

In [16]:
# Read the CSV file into a DataFrame

#bosch-ai
df_3 = pd.read_csv(file_3)
#default eda parameters
df_2 = pd.read_csv(file_2)

In [18]:
df_3.columns

Index(['corpus', 'doc_id', 'sent_id', 'eg_id', 'index', 'text',
       'causal_text_w_pairs', 'num_rs'],
      dtype='object')

In [19]:
df_3_filtered = df_3[df_3['num_rs'] == 1]
df_3_filtered

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the state be alleged they make up hacked saba...,['the state be alleged <ARG1>they make up hack...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,"""the farmworkers ' strike strike resumed on tu...","[""<ARG1>the farmworkers ' strike strike resume...",1
3,cnc,train_1003_10003,10003,0,cnc_train_103_1003_10003_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1
8,cnc,train_1008_10008,10008,0,cnc_train_108_1008_10008_10,'protesters are angry at the police s slow res...,['<ARG1>protesters are angry</ARG1> <SIG0>at</...,1
...,...,...,...,...,...,...,...,...
3239,cnc,train_4239_13239,13239,0,cnc_train_3339_4239_13239_10,'the cpim leader said that while cpim workers ...,['the cpim leader said that while cpim workers...,1
3240,cnc,train_4240_13240,13240,0,cnc_train_3340_4240_13240_10,'mr make up chandy was make up atomic number n...,['<ARG1>mr make up chandy was make up atomic n...,1
3241,cnc,train_4241_13241,13241,0,cnc_train_3341_4241_13241_10,'mr chandy was not condemning violence by rss ...,['<ARG1>mr chandy was not condemning violence ...,1
3244,cnc,train_4244_13244,13244,0,cnc_train_3344_4244_13244_10,'tirupur protests against lack city manager as...,['tirupur protests against lack city manager a...,1
3245,cnc,train_4245_13245,13245,0,cnc_train_3345_4245_13245_10,'tirupur protests against lack of amenities no...,['tirupur protests against lack of amenities n...,1

In [20]:
df_2_filtered = df_2[df_2['num_rs'] == 1]
df_2_filtered

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the say alleged they hacked sabata petros cha...,['the say alleged <ARG1>they hacked sabata pet...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state aver they hacked sabata petros chal...,['the state aver <ARG1>they hacked sabata petr...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
3,cnc,train_1003_10003,10003,0,cnc_train_103_1003_10003_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
4,cnc,train_1004_10004,10004,0,cnc_train_104_1004_10004_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
...,...,...,...,...,...,...,...,...
8110,cnc,train_9110_18110,18110,0,cnc_train_8210_9110_18110_10,post 'tirupur protests against lack of ameniti...,post ['tirupur protests against lack of amenit...,1
8111,cnc,train_9111_18111,18111,0,cnc_train_8211_9111_18111_10,'tirupur protests against lack of amenities no...,['tirupur protests against lack of amenities n...,1
8112,cnc,train_9112_18112,18112,0,cnc_train_8212_9112_18112_10,'tirupur dissent against lack of amenities nov...,['tirupur dissent against lack of amenities no...,1
8113,cnc,train_9113_18113,18113,0,cnc_train_8213_9113_18113_10,'tirupur protests against lack of amenities no...,['tirupur protests against lack of amenities n...,1
8114,cnc,train_9114_18114,18114,0,cnc_train_8214_9114_18114_10,'tirupur protests against lack of amenities no...,['tirupur protests against lack of amenities n...,1

In [21]:
df_3_filtered.to_csv('1_processed_eda_3_output_transformed_train_subtask2.csv', index=None)

In [22]:
df_2_filtered.to_csv('1_processed_eda_2_output_transformed_train_subtask2.csv', index=None)

In [23]:
df_3_filtered.shape

(2210, 8)

In [24]:
df_2_filtered.shape

(5525, 8)

In [38]:
import re

def remove_words_before_bracket(sentence):
    if isinstance(sentence, str):
        # Use regular expression to remove words before "['" or '["'
        result = re.sub(r'.*?(\[\'| \[")', r'\1', sentence)
        return result
    elif isinstance(sentence, list):
        # Process each element of the list
        return [remove_words_before_bracket(element) for element in sentence]
    else:
        # Handle unsupported types
        raise ValueError("Unsupported input type. Expected string or list.")

# Example sentences
sentence_1 = "dissident ['<ARG1>the protesters mahratti marathi shouted slogans against the karnataka cm</ARG1> mahratti , <ARG0><SIG0>demanding</SIG0> that belgaum , along with marathi speaking areas blackguard mahratti in public speaking that state , mahratti be united states department of state merged marathi marathi with marathi maharashtra</ARG0> marathi ']"
sentence_2 = "present tense atomic number present ['<ARG1>an integrated comprehensive examination steel atomic number present plant , agriculture ask and mineral comprehensive examination front breast based industries should be set up in official functionary kadapa engagement district</ARG1> <SIG0>for</SIG0> <ARG0>ensuring its comprehensive examination comprehensive development</ARG0> and generate employment usda , cpim agriculture district world health organization secretary b narayana demanded while nerve addressing engagement beget party functionaries who staged dharna in front base of kadapa base functionary collectorate on thursday ']"
sentence_3 = ['on thursday , chen daoxiang , the head of the chinese army garrison in hong kong , said <ARG1>the military was determined to protect [ the ] national sovereignty of hong kong and would help put down the intolerable unrest</ARG1> <SIG0>if</SIG0> <ARG0>requested</ARG0> ']
sentence_4 = ['on th , subgenus chen daoxiang , the headspring of the taiwanese united states army fort in hong kong , enunciate <ARG1>the military machine was ascertain to protect [ the ] interior reign of hong kong and would assistance frame down the unendurable unrest</ARG1> <SIG0>if</SIG0> <ARG0>requested</ARG0> ']


# Apply the function to each sentence
processed_sentence_1 = remove_words_before_bracket(sentence_1)
processed_sentence_2 = remove_words_before_bracket(sentence_2)
processed_sentence_3 = remove_words_before_bracket(sentence_3)
processed_sentence_4 = remove_words_before_bracket(sentence_4)
# Print the results
print(processed_sentence_1)
print(processed_sentence_2)
print(processed_sentence_3)
print(processed_sentence_4)

['<ARG1>the protesters mahratti marathi shouted slogans against the karnataka cm</ARG1> mahratti , <ARG0><SIG0>demanding</SIG0> that belgaum , along with marathi speaking areas blackguard mahratti in public speaking that state , mahratti be united states department of state merged marathi marathi with marathi maharashtra</ARG0> marathi ']
['<ARG1>an integrated comprehensive examination steel atomic number present plant , agriculture ask and mineral comprehensive examination front breast based industries should be set up in official functionary kadapa engagement district</ARG1> <SIG0>for</SIG0> <ARG0>ensuring its comprehensive examination comprehensive development</ARG0> and generate employment usda , cpim agriculture district world health organization secretary b narayana demanded while nerve addressing engagement beget party functionaries who staged dharna in front base of kadapa base functionary collectorate on thursday ']
['on thursday , chen daoxiang , the head of the chinese army garrison in hong kong , said <ARG1>the military was determined to protect [ the ] national sovereignty of hong kong and would help put down the intolerable unrest</ARG1> <SIG0>if</SIG0> <ARG0>requested</ARG0> ']
['on th , subgenus chen daoxiang , the headspring of the taiwanese united states army fort in hong kong , enunciate <ARG1>the military machine was ascertain to protect [ the ] interior reign of hong kong and would assistance frame down the unendurable unrest</ARG1> <SIG0>if</SIG0> <ARG0>requested</ARG0> ']

In [43]:
import re

def remove_words_before_bracket(sentence):
    if isinstance(sentence, str):
        # Use regular expression to remove words before "['" or '["'
        result = re.sub(r'.*?(\[\'| \[")', r'\1', sentence)
        return result
    elif isinstance(sentence, list):
        # Process each element of the list
        return [remove_words_before_bracket(element) for element in sentence]
    else:
        # Handle unsupported types
        raise ValueError("Unsupported input type. Expected string or list.")

In [44]:
# Read the CSV file into a DataFrame

#bosch-ai
df_3 = pd.read_csv('1_processed_eda_3_output_transformed_train_subtask2.csv')
#default eda parameters
df_2 = pd.read_csv('1_processed_eda_2_output_transformed_train_subtask2.csv')

In [45]:
df_3['causal_text_w_pairs'] = df_3['causal_text_w_pairs'].apply(remove_words_before_bracket)

# Print the updated DataFrame
df_3.head(10)

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the state be alleged they make up hacked saba...,['the state be alleged <ARG1>they make up hack...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,"""the farmworkers ' strike strike resumed on tu...","[""<ARG1>the farmworkers ' strike strike resume...",1
3,cnc,train_1003_10003,10003,0,cnc_train_103_1003_10003_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1
4,cnc,train_1008_10008,10008,0,cnc_train_108_1008_10008_10,'protesters are angry at the police s slow res...,['<ARG1>protesters are angry</ARG1> <SIG0>at</...,1
5,cnc,train_1009_10009,10009,0,cnc_train_109_1009_10009_10,'protesters are angry at the police s slow res...,['<ARG1>protesters are angry</ARG1> <SIG0>at</...,1
6,cnc,train_1010_10010,10010,0,cnc_train_110_1010_10010_10,'the wildness in yuen long has heightened taut...,['<ARG0>the wildness in yuen long</ARG0> <SIG0...,1
7,cnc,train_1011_10011,10011,0,cnc_train_111_1011_10011_10,'the violence in yuen long has heightened tens...,['<ARG0>the violence in yuen long</ARG0> <SIG0...,1
8,cnc,train_1014_10014,10014,0,cnc_train_114_1014_10014_10,"'hailey leung , a university scholar who has b...","['hailey leung , a university scholar who has ...",1
9,cnc,train_1015_10015,10015,0,cnc_train_115_1015_10015_10,"'hailey leung , a university student who has b...","['hailey leung , a university student who has ...",1

In [48]:
df_3[df_3['sent_id'] == 10145]['causal_text_w_pairs']

95    ['on thursday , chen daoxiang , the head of th...
Name: causal_text_w_pairs, dtype: object

In [50]:
df_3.to_csv('del_1_processed_eda_3_output_transformed_train_subtask2.csv', index=None)

In [51]:
df_2['causal_text_w_pairs'] = df_2['causal_text_w_pairs'].apply(remove_words_before_bracket)

# Print the updated DataFrame
df_2.head(10)

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the say alleged they hacked sabata petros cha...,['the say alleged <ARG1>they hacked sabata pet...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state aver they hacked sabata petros chal...,['the state aver <ARG1>they hacked sabata petr...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
3,cnc,train_1003_10003,10003,0,cnc_train_103_1003_10003_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
4,cnc,train_1004_10004,10004,0,cnc_train_104_1004_10004_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
5,cnc,train_1005_10005,10005,0,cnc_train_105_1005_10005_10,"""the farmworkers ' impress resumed on tuesday ...","[""<ARG1>the farmworkers ' impress resumed on t...",1
6,cnc,train_1006_10006,10006,0,cnc_train_106_1006_10006_10,"work stoppage ""the farmworkers ' strike resume...","[""<ARG1>the farmworkers ' strike resumed on t...",1
7,cnc,train_1007_10007,10007,0,cnc_train_107_1007_10007_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1
8,cnc,train_1008_10008,10008,0,cnc_train_108_1008_10008_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1
9,cnc,train_1009_10009,10009,0,cnc_train_109_1009_10009_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1

In [52]:
df_2.to_csv('del_1_processed_eda_2_output_transformed_train_subtask2.csv', index=None)

In [53]:
# Read the CSV file into a DataFrame

#bosch-ai
df_3 = pd.read_csv('del_1_processed_eda_3_output_transformed_train_subtask2.csv')
#default eda parameters
df_2 = pd.read_csv('del_1_processed_eda_2_output_transformed_train_subtask2.csv')

In [55]:
# Remove '[' and ']' from the 'causal_text_w_pairs' column in df_3
df_3['causal_text_w_pairs'] = df_3['causal_text_w_pairs'].str.replace('[\[\]]', '', regex=True)

# Remove '[' and ']' from the 'causal_text_w_pairs' column in df_2
#df_2['causal_text_w_pairs'] = df_2['causal_text_w_pairs'].str.replace('[\[\]]', '', regex=True)

# Print the updated DataFrames
df_3.head()
#print(df_2.head())

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the state be alleged they make up hacked saba...,'the state be alleged <ARG1>they make up hacke...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state alleged they hacked sabata petros c...,'the state alleged <ARG1>they hacked sabata pe...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,"""the farmworkers ' strike strike resumed on tu...","""<ARG1>the farmworkers ' strike strike resumed...",1
3,cnc,train_1003_10003,10003,0,cnc_train_103_1003_10003_10,"""the farmworkers ' strike resumed on tuesday w...","""<ARG1>the farmworkers ' strike resumed on tue...",1
4,cnc,train_1008_10008,10008,0,cnc_train_108_1008_10008_10,'protesters are angry at the police s slow res...,'<ARG1>protesters are angry</ARG1> <SIG0>at</S...,1

In [56]:
df_3.to_csv('del_2_processed_eda_3_output_transformed_train_subtask2.csv', index=None)

In [57]:
df_2['causal_text_w_pairs'] = df_2['causal_text_w_pairs'].str.replace('[\[\]]', '', regex=True)
df_2.to_csv('del_2_processed_eda_2_output_transformed_train_subtask2.csv', index=None)

In [59]:
df_2.shape

(5525, 8)

In [60]:
df_3.shape

(2210, 8)

In [61]:
# Read the CSV file into a DataFrame

#bosch-ai
df_3 = pd.read_csv('del_2_processed_eda_3_output_transformed_train_subtask2.csv')
#default eda parameters
df_2 = pd.read_csv('del_2_processed_eda_2_output_transformed_train_subtask2.csv')

In [62]:
# Add '[' at the start and ']' at the end of each sentence in df_3
df_3['causal_text_w_pairs'] = '[' + df_3['causal_text_w_pairs'] + ']'

# Add '[' at the start and ']' at the end of each sentence in df_2
df_2['causal_text_w_pairs'] = '[' + df_2['causal_text_w_pairs'] + ']'

In [65]:
df_3.head(3)

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the state be alleged they make up hacked saba...,['the state be alleged <ARG1>they make up hack...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,"""the farmworkers ' strike strike resumed on tu...","[""<ARG1>the farmworkers ' strike strike resume...",1

In [66]:
df_2.head(3)

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the say alleged they hacked sabata petros cha...,['the say alleged <ARG1>they hacked sabata pet...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state aver they hacked sabata petros chal...,['the state aver <ARG1>they hacked sabata petr...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1

In [67]:
df_3.to_csv('del_3_processed_eda_3_output_transformed_train_subtask2.csv', index=None)

In [68]:
df_2.to_csv('del_3_processed_eda_2_output_transformed_train_subtask2.csv', index=None)

In [69]:
# Read the CSV file into a DataFrame

#bosch-ai
df_3 = pd.read_csv('del_3_processed_eda_3_output_transformed_train_subtask2.csv')
#default eda parameters
df_2 = pd.read_csv('del_3_processed_eda_2_output_transformed_train_subtask2.csv')

In [70]:
df_3['text'] = df_3['causal_text_w_pairs'].apply(lambda x: re.sub(r'<(/?ARG[012]|/?SIG[012])>', '', x))

# Remove square brackets from the 'text' column sentences
df_3['text'] = df_3['text'].apply(lambda x: re.sub(r'[\[\]]', '', x))
df_3.head(10)

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the state be alleged they make up hacked saba...,['the state be alleged <ARG1>they make up hack...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,"""the farmworkers ' strike strike resumed on tu...","[""<ARG1>the farmworkers ' strike strike resume...",1
3,cnc,train_1003_10003,10003,0,cnc_train_103_1003_10003_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1
4,cnc,train_1008_10008,10008,0,cnc_train_108_1008_10008_10,'protesters are angry at the police s slow res...,['<ARG1>protesters are angry</ARG1> <SIG0>at</...,1
5,cnc,train_1009_10009,10009,0,cnc_train_109_1009_10009_10,'protesters are angry at the police s slow res...,['<ARG1>protesters are angry</ARG1> <SIG0>at</...,1
6,cnc,train_1010_10010,10010,0,cnc_train_110_1010_10010_10,'the wildness in yuen long has heightened taut...,['<ARG0>the wildness in yuen long</ARG0> <SIG0...,1
7,cnc,train_1011_10011,10011,0,cnc_train_111_1011_10011_10,'the violence in yuen long has heightened tens...,['<ARG0>the violence in yuen long</ARG0> <SIG0...,1
8,cnc,train_1014_10014,10014,0,cnc_train_114_1014_10014_10,"'hailey leung , a university scholar who has b...","['hailey leung , a university scholar who has ...",1
9,cnc,train_1015_10015,10015,0,cnc_train_115_1015_10015_10,"'hailey leung , a university student who has b...","['hailey leung , a university student who has ...",1

In [71]:
df_2['text'] = df_2['causal_text_w_pairs'].apply(lambda x: re.sub(r'<(/?ARG[012]|/?SIG[012])>', '', x))

# Remove square brackets from the 'text' column sentences
df_2['text'] = df_2['text'].apply(lambda x: re.sub(r'[\[\]]', '', x))
df_2.head(10)

,corpus,doc_id,sent_id,eg_id,index,text,causal_text_w_pairs,num_rs
0,cnc,train_1000_10000,10000,0,cnc_train_100_1000_10000_10,'the say alleged they hacked sabata petros cha...,['the say alleged <ARG1>they hacked sabata pet...,1
1,cnc,train_1001_10001,10001,0,cnc_train_101_1001_10001_10,'the state aver they hacked sabata petros chal...,['the state aver <ARG1>they hacked sabata petr...,1
2,cnc,train_1002_10002,10002,0,cnc_train_102_1002_10002_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
3,cnc,train_1003_10003,10003,0,cnc_train_103_1003_10003_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
4,cnc,train_1004_10004,10004,0,cnc_train_104_1004_10004_10,'the state alleged they hacked sabata petros c...,['the state alleged <ARG1>they hacked sabata p...,1
5,cnc,train_1005_10005,10005,0,cnc_train_105_1005_10005_10,"""the farmworkers ' impress resumed on tuesday ...","[""<ARG1>the farmworkers ' impress resumed on t...",1
6,cnc,train_1006_10006,10006,0,cnc_train_106_1006_10006_10,"""the farmworkers ' strike resumed on tuesday ...","[ ""<ARG1>the farmworkers ' strike resumed on t...",1
7,cnc,train_1007_10007,10007,0,cnc_train_107_1007_10007_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1
8,cnc,train_1008_10008,10008,0,cnc_train_108_1008_10008_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1
9,cnc,train_1009_10009,10009,0,cnc_train_109_1009_10009_10,"""the farmworkers ' strike resumed on tuesday w...","[""<ARG1>the farmworkers ' strike resumed on tu...",1

In [72]:
df_3.to_csv('del_4_processed_eda_3_output_transformed_train_subtask2.csv', index=None)
df_2.to_csv('del_4_processed_eda_2_output_transformed_train_subtask2.csv', index=None)